name: Build Release

on:
  release:
    types: [published]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  firmware:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - board: pico
            suffix: rp2040
          - board: pico2
            suffix: rp2350

    env:
      FIRMWARE_FILENAME: picomso-${{ matrix.suffix }}-${{ github.ref_name }}.uf2

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Git tags
        run: git fetch --prune

      - name: Build firmware
        uses: samyarsadat/Pico-Build-Action@v1
        with:
          source_dir: "firmware/app"
          output_dir: "build"
          cmake_args: "-DCMAKE_BUILD_TYPE=Release -DPICO_BOARD=${{ matrix.board }}"

      - name: Locate firmware
        run: |
          find . -name "*.uf2"

      - name: Prepare release artifact
        run: |
          mkdir -p dist
          cp firmware/app/build/*.uf2 dist/${{ env.FIRMWARE_FILENAME }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ env.FIRMWARE_FILENAME }}

      - name: Generate attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: dist/${{ env.FIRMWARE_FILENAME }}
          github-token: ${{ secrets.TOKEN }}